kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: cups-debian
  namespace: cups
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'cups-debian:latest'
  resources: {}
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'debian:buster'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |-

      FROM debian:buster

      ARG TARGETPLATFORM
      ARG BUILDPLATFORM
      RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM" 

      RUN apt-get update && apt-get install -y \
        sudo \
        locales \
        whois \
        cups \
        cups-client \
        cups-bsd \
        printer-driver-all \
        printer-driver-gutenprint \
        hpijs-ppds \
        hp-ppd  \
        hplip \
        printer-driver-foo2zjs

      ENV LANG=en_US.UTF-8 \
        LC_ALL=en_US.UTF-8 \
        LANGUAGE=en_US:en

      RUN useradd \
        --groups=sudo,lp,lpadmin \
        --create-home \
        --home-dir=/home/print \
        --shell=/bin/bash \
        --password=$(mkpasswd print) \
        print \
        && sed -i '/%sudo[[:space:]]/ s/ALL[[:space:]]*$/NOPASSWD:ALL/' /etc/sudoers \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/* \
        && mkdir /var/lib/apt/lists/partial

      # Might not be necessary since we are using configmaps now.
      # alternatively make a `etc-cups` directory with a default `cupsd.conf`
      # COPY etc-cups/cupsd.conf /etc/cups/cupsd.conf

      EXPOSE 31631

      ENTRYPOINT ["/usr/sbin/cupsd", "-f"]
  runPolicy: Serial
