apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cups
  name: cups
  namespace: cups
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cups
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cups
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cups/cups-debian
        imagePullPolicy: IfNotPresent
        name: cups
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cups/
          name: cupsd-conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: cupsd.conf
            path: cupsd.conf
          name: cupsd-conf
        name: cupsd-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cups
  name: cups
  namespace: cups
  selfLink: /api/v1/namespaces/default/services/cups
spec:
  clusterIP: 10.217.4.50
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31631
    port: 31631
    protocol: TCP
    targetPort: 31631
  selector:
    app: cups
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

